name: Cypress Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Install Cypress
        run: npm install cypress --save-dev
      - name: Install cucumber
        run: npm install --save-dev @cucumber/cucumber
      - name: Run Cypress test
        run: npx cypress run --browser chrome --env allure=true,allureReuseAfterSpec=true
      - name: Reports Generate
        if: ${{ failure() || success() }}
        run: npx allure generate allure-results --clean -o allure-report
      - name: Upload Report
        uses: actions/upload-pages-artifact@v1
        if: ${{ failure() || success() }}
        with:
          path: ./allure-report
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
